// Mocks generated by Mockito 5.3.2 from annotations
// in bettertwitter/test/screens/add_tweet/ui/add_tweet_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bettertwitter/screens/add_tweet/bloc/add_tweet_bloc.dart'
    as _i3;
import 'package:bettertwitter/screens/add_tweet/repository/add_tweet_repository.dart'
    as _i2;
import 'package:bloc/bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddTweetRepository_0 extends _i1.SmartFake
    implements _i2.AddTweetRepository {
  _FakeAddTweetRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddTweetState_1 extends _i1.SmartFake implements _i3.AddTweetState {
  _FakeAddTweetState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddTweetBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTweetBloc extends _i1.Mock implements _i3.AddTweetBloc {
  MockAddTweetBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddTweetRepository get manipulateTweetRepository => (super.noSuchMethod(
        Invocation.getter(#manipulateTweetRepository),
        returnValue: _FakeAddTweetRepository_0(
          this,
          Invocation.getter(#manipulateTweetRepository),
        ),
      ) as _i2.AddTweetRepository);
  @override
  set manipulateTweetRepository(
          _i2.AddTweetRepository? _manipulateTweetRepository) =>
      super.noSuchMethod(
        Invocation.setter(
          #manipulateTweetRepository,
          _manipulateTweetRepository,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.AddTweetState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAddTweetState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AddTweetState);
  @override
  _i4.Stream<_i3.AddTweetState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i3.AddTweetState>.empty(),
      ) as _i4.Stream<_i3.AddTweetState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void add(_i3.ManipulateTweetEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i3.ManipulateTweetEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i3.AddTweetState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i3.ManipulateTweetEvent>(
    _i5.EventHandler<E, _i3.AddTweetState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i5.Transition<_i3.ManipulateTweetEvent, _i3.AddTweetState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void onChange(_i5.Change<_i3.AddTweetState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AddTweetEvent].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTweetEvent extends _i1.Mock implements _i3.AddTweetEvent {
  MockAddTweetEvent() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tweet => (super.noSuchMethod(
        Invocation.getter(#tweet),
        returnValue: '',
      ) as String);
  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}

/// A class which mocks [AddTweetState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTweetState extends _i1.Mock implements _i3.AddTweetState {
  MockAddTweetState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}

/// A class which mocks [AddTweetInitial].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTweetInitial extends _i1.Mock implements _i3.AddTweetInitial {
  MockAddTweetInitial() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}

/// A class which mocks [AddTweetLoading].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTweetLoading extends _i1.Mock implements _i3.AddTweetLoading {
  MockAddTweetLoading() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}

/// A class which mocks [AddTweetSuccess].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTweetSuccess extends _i1.Mock implements _i3.AddTweetSuccess {
  MockAddTweetSuccess() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}

/// A class which mocks [AddTweetFailure].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTweetFailure extends _i1.Mock implements _i3.AddTweetFailure {
  MockAddTweetFailure() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
}
